### ISSUE TITLE
Run tests on continuous integration server

### ISSUE THREAD

**Issue by tompollard** [kjohnsson/modality#5]
Link repository to continuous integration server (e.g. Travis - https://travis-ci.org/) for automated testing.

**Comment by tompollard** [comment]
@kjohnsson for us to set up continuous testing on Travis, we will need to link the repository to a Travis account (https://travis-ci.org/). 

I'm happy to do this if you don't mind adding me as a collaborator on the project (@tompollard), otherwise you should be able to do it by creating an account on Travis and following the instructions to add the repository.

**Comment by kjohnsson** [comment]
I have added the modality repo on my Travis account and added a .travis.yml file. Currently the build fails since dependencies are not properly handled in setup.py, I think this is one of the issues that you have made already so I left it that way for now.

**Comment by tompollard** [comment]
Thanks @kjohnsson, I'll take a look at the tests soon.
